### ISSUE TITLE
Using quicklisp to install qlot doesn't setup qlot shell command

### ISSUE THREAD

**Issue by nmunro** [fukamachi/qlot#101]
Using quicklisp to install qlot doesn't setup qlot shell command, I am using fish shell on the latest MacOS (10.15.3) and I used the following command to install.

(ql:quickload :qlot)

However the shell command wasn't installed, perhaps I'm doing it wrong, but the documentation seems to suggest it should just work.

**Comment by fukamachi** [comment]
[Install Roswell via Homebrew](https://github.com/roswell/roswell/wiki/Installation#mac-os-x--homebrew) and run `ros install qlot`. It will install the shell command to `~/.roswell/bin`.

**Comment by naryl** [comment]
This still looks like an issue. There are two ways to install Qlot.
1. Use Roswell, and run it with `qlot` shell command.
2. Use Quicklisp, and use the lisp API.
The first one works nicely. The second one is completely undocumented, but still available.

**Comment by momozor** [comment]
An example to do *install* operation with lisp API which I found is by running `(qlot/install:install-qlfile "qlfile")`. There are also update equivalent available as well `QLOT/INSTALL:UPDATE-QLFILE`.

Also yeah, have to agree with @naryl regarding the documentation, starting with basic and common tasks like install, update, etc.

**Comment by svetlyak40wt** [comment]
I've created a short instruction how to use Qlot from the REPL: https://github.com/svetlyak40wt/qlot-without-roswell

You don't have to load `qlot/cli`.

**Comment by fukamachi** [comment]
Installation is completely renewed. Please try it with the latest version and open a new issue if you find a problem.
