### ISSUE TITLE
Unclear how to use newly defined distribution in qlfile

### ISSUE THREAD

**Issue by cvchaparro** [fukamachi/qlot#102]
I'm working on an application and I'd like to use `qlot` for managing local dependencies.  As part of this I wanted to test out [Radiance](https://github.com/Shirakumo/radiance).  In the documentation (for Radiance), it states that it can be downloaded via a custom Quicklisp distribution.  As such, I wrote my `qlfile` as follows:

```
dist shirakumo http://dist.tymoon.eu/shirakumo.txt
shirakumo radiance
```

When I run `qlot install`, it gives me an error stating that `shirakumo` is an unknown source.  I also tried using `ql` and `ultralisp` as sources to no avail.  (To be honest, I didn't expect it to work that way either but I figured I'd at least try.)  I realize that I can use different sources (i.e. `git`, `github`, `http`, etc) however those don't appear to be working for me at this time (I'm probably missing something) and it seems like the natural way to do it is adding the distribution anyways.

To that end, I've been searching for a way to actually use the distribution I added.  My original thought was that it would work similar to using the `ql` or `ultralisp` distributions, except of course the `source` would be whatever I named the new distribution (`shirakumo` in this case).

My question: Is there a way to actually do this, yet?  If not, I'd be happy to try my hand at providing an implementation but I'm still very much in the learning phase when it comes to Common Lisp development so it might take me a bit to get anything worth merging in.  However, if you're willing to be patient while I work on it, I'm willing to write the code. :smiley:

P.S. The most similar issue I have found related to this, so far, is #58 (from September 2018) where the `dist` source was added but the code looks different than it was after the PR where that was resolved so I'm still not sure where this would be addressed.  Any pointers would be greatly appreciated; thanks!

**Comment by cvchaparro** [comment]
I've done a bit of digging and it looks like this may be able to be resolved using a macro that, upon encountering a line of the form `dist <name> <url>`, it creates a new valid source out of `<name>`.  I'm doing a bit of experimenting on this in my own fork of this repository.  Will update with a PR as I get closer to a working solution.

**Comment by svetlyak40wt** [comment]
I also have the same issue:

```
qlot: Error raised while parsing '/Users/art/projects/lisp/fin/qlfile' at line 5:

  org.borodust.bodge.testing trivial-gamekit

Unknown source: ORG.BORODUST.BODGE.TESTING
```

The full content of the `qlfile` is:

```
dist ultralisp http://dist.ultralisp.org/
dist org.borodust.bodge.testing http://bodge.borodust.org/dist/org.borodust.bodge.testing.txt

org.borodust.bodge.testing trivial-gamekit
```

However, without `org.borodust.bodge.testing trivial-gamekit` everything is installed.

@cvchaparro the last mentioned `dist` will have a priority over previous. And you don't need to specify `shirakumo radiance` explicitly:

```
[art@lispbook:...ojects/lisp/foo]% cat qlfile
dist shirakumo http://dist.tymoon.eu/shirakumo.txt

[art@lispbook:...ojects/lisp/foo]% qlot install
Installing Quicklisp to /Users/art/projects/lisp/foo/.qlot/ ...
; Fetching #<URL "http://beta.quicklisp.org/quicklisp.lisp">
; 55.80KB
==================================================
57,144 bytes in 0.03 seconds (1993.02KB/sec)
Reading '/Users/art/projects/lisp/foo/qlfile'...
Installing dist "quicklisp" version "2020-03-25".
Downloading http://beta.quicklisp.org/dist/quicklisp/2020-03-25/releases.txt
##########################################################################
Downloading http://beta.quicklisp.org/dist/quicklisp/2020-03-25/systems.txt
##########################################################################
Installing dist "shirakumo" version "2020.04.20_07-24-00-GMT".
Downloading http://dist.tymoon.eu/shirakumo/2020.04.20_07-24-00-GMT/releases.txt
##########################################################################
Downloading http://dist.tymoon.eu/shirakumo/2020.04.20_07-24-00-GMT/systems.txt
##########################################################################
Ensuring 0 dependencies installed.
Successfully installed.

[art@lispbook:...ojects/lisp/foo]% qlot exec ros run                                                                (master↑10|✚2…)
* (ql:quickload :radiance)
To load "radiance":
  Load 1 ASDF system:
    asdf
  Install 21 Quicklisp releases:
    alexandria babel bordeaux-threads cl-fad cl-ppcre
    closer-mop documentation-utils form-fiddle
    lambda-fiddle local-time modularize modularize-hooks
    modularize-interfaces puri radiance trivial-arguments
    trivial-features trivial-indent trivial-mimes
    trivial-package-local-nicknames ubiquitous
; Fetching #<URL "http://beta.quicklisp.org/archive/ubiquitous/2019-07-10/ubiquitous-20190710-git.tgz">

...

8,913 bytes in 0.00 seconds (0.00KB/sec)
; Fetching #<URL "http://dist.tymoon.eu/shirakumo/archive/modularize-2020.04.20_07-24-07-GMT.tgz">
; 87.89KB
==================================================
89,995 bytes in 0.09 seconds (976.51KB/sec)
; Fetching #<URL "http://dist.tymoon.eu/shirakumo/archive/radiance-2020.04.20_07-24-08-GMT.tgz">
; 6506.89KB
==================================================
6,663,051 bytes in 0.69 seconds (9430.27KB/sec)
; Loading "radiance"
[package trivial-indent]..........................
[package documentation-utils].....................
[package trivial-package-local-nicknames].........
[package modularize]..............................
[package org.shirakumo.radiance.lib.modularize.user].
..................................................
[package closer-mop]..............................
[package closer-common-lisp]......................
[package closer-common-lisp-user].................
[package trivial-arguments].......................
[package lambda-fiddle]...........................
[package modularize-hooks]........................
[package modularize-interfaces]...................
[package ubiquitous]..............................
[package alexandria.1.0.0]........................
[package bordeaux-threads]........................
[package cl-ppcre]................................
..................................................
[package trivial-mimes]...........................
[package cl-fad]..................................
[package path]....................................
[package local-time]..............................
[package form-fiddle].............................
[package babel-encodings].........................
[package babel]...................................
..................................................
[package puri]....................................
.........................
(:RADIANCE)

* (ql:where-is-system :radiance)
#P"/Users/art/projects/lisp/foo/.qlot/dists/shirakumo/software/radiance-2020.04.20_07-24-08-GMT/"
```

**Comment by omrisim210** [comment]
I'm getting the same error while trying to install trivial-gamekit from borodust's distribution (both the regular and the testing one), I've done everything the same as in the other comments.

I'm not too familiar with the qlot source code, but perhaps the dist name is making the parser choke on the dists when you try to use them but not when you add them? It's the only thing I can think about, since borodust's distributions have periods in their name.

**Comment by cvchaparro** [comment]
First off, sorry for taking so long to get back to this - been short on time due to work and I do most of my development over at Gitlab.com so I don't check Github very often.  That said, interesting point @svetlyak40wt, I will try your way instead of what I was doing.

Also, I'm still happy to try and fix this (assuming it's actually a bug as opposed to just my not using it correctly).  Let me see if I can figure something out.

**Comment by cvchaparro** [comment]
I just tested this again with the recommendation of @svetlyak40wt and it would seem I was just trying to use it incorrectly.

When I tested this, I saw that Qlot parsed my `*.asd` files and (I assume, though I didn't look at the code to confirm) installed packages based on my listed dependencies there so I guess my question, then, would be is there really any benefit to putting dependencies that are in a Quicklisp distribution in the qlfile at all? As long as the distribution is versioned, wouldn't it already install the correct versions, anyways?

**Comment by svetlyak40wt** [comment]
ASDF will install a library from a distribution having the largest priority. It does not account for distribution versions or ASDF system versions.

**Comment by cvchaparro** [comment]
Yes, I understand that is true for ASDF, but I was referring to Qlot for which I don't think it should be true. Otherwise, what's the point of having Qlot to begin with? Perhaps an example of what I'm asking would paint a better picture.

Assume I have the following system definition file (with irrelevant information elided):

```lisp
(defsystem "my-app"
  :depends-on (:alexandria :radiance :personal-utils))
```

If my `qlfile` looks like this:

```
dist shirakumo http://dist.tymoon.eu/shirakumo.txt 2020.10.01_19-44-06-GMT

# Some hypothetical private library not included in any quicklisp distribution
git personal-utils git@gitlab.com:cvchaparro/personal-utils.git
```

My question boils down to this: Does it make sense to include anything other than the private Git project in the above `qlfile`? From what I can tell, it doesn't because Qlot will automatically pull `:alexandria` and `:radiance` from their respective Quicklisp distributions. That said, I sense there may be something I'm missing so I want to see if this is the correct way of thinking about how Qlot works.

Thank you for your help in understanding this. :+1:

**Comment by svetlyak40wt** [comment]
Everything Qlot does it set up a quicklisp compatible distribution for every line from a `qlfile`.

Lines at the bottom have a priority. In your example, if `gitlab.com:cvchaparro/personal-utils` also has `radiance.asd`, then this system will be loaded from the `personal-utils` instead of http://dist.tymoon.eu.

For example, if content of qlfile is like this:

```
dist shirakumo http://dist.tymoon.eu/shirakumo.txt 2020.10.01_19-44-06-GMT

# Some hypothetical private library not included in any quicklisp distribution
git defmain https://github.com/40ants/defmain
```

Then quicklisp client will be configured to see three dists (first has the higher priority):

```lisp
CL-USER> (loop for dist in (sort (ql-dist:all-dists)
                                 #'>
                                 :key #'ql-dist:preference)
               for priority = (ql-dist:preference dist)
               do (format t "~A: ~A~%"
                          dist
                          priority))
#<DIST defmain git-40584bb75d848c5bb6f9c1a8ba8716ef66303c1b>: 3848288961
#<DIST shirakumo 2020.10.01_19-44-06-GMT>: 3848288960
#<DIST quicklisp 2021-12-09>: 3848288959
```

Version numbers in `qlfile` only pin a version forcing quicklisp to use this one instead of latest.

**Comment by cvchaparro** [comment]
Wow, I see. I see that my mistake was in assuming Qlot was similar to Python's `venv` and `pip`, for example. But with your explanation, I see that this is not the way to think of Qlot. Rather I should think of it as setting up different locations from which to pull packages (using the Python example).

Thank you, again, for helping me understand how this is working. I'll close this since it was an issue with me and not the project.
