### ISSUE TITLE
RFC: project/repo name mismatches with github sources

### ISSUE THREAD

**Issue by mtstickney** [fukamachi/qlot#110]
I just ran into an install issue with a github source, and I'm not sure what the expected behavior is, so I can't tell if it's a bug or just a missing error/warning. The problem is when you have a github source, and the project name doesn't match the repo name (e.g. `github cl+ssl cl-plus-ssl/cl-plus-ssl`).

What happens is that the github source re-uses the archive that it downloads from github as the dist archive for ql installation. The archive from github uses a root directory based on the repo name (`cl-plus-ssl/`), but qlot has generated the metadata on the assumption that it will be installed under the project name (`software/cl+ssl-<version>`), so it is unable to find the system when it tries to load it.

Are github sources intended to allow the project name in the source file to override the repo name on github, or is this a mis-configuration and they should always be made to match? If it's a bug, we should be able to re-use the github archive in most cases, but we'd have to check for a matching project/repo name first. If it's a mis-configuration, where would be best place be to put a "you can't have mis-matched names in a github source" warning? I would think somewhere near the parser, but I haven't been in that code yet.

**Comment by fukamachi** [comment]
A project name in qlfile is an identifier for dependencies in the project. There are no limitations.
The newer Qlot accepts `github cl-plus-ssl/cl-plus-ssl` and uses `cl-plus-ssl` as its project name automatically.
