### ISSUE TITLE
Where is bundle command?

### ISSUE THREAD

**Issue by svetlyak40wt** [fukamachi/qlot#113]
Help string still refer the `bundle` subcommand:
https://github.com/fukamachi/qlot/blob/master/roswell/qlot.ros#L36-L37
but there is no any code to execute.

When and why it was removed?

**Comment by svetlyak40wt** [comment]
Oh, I found that it was removed in 0.10 release:

https://github.com/fukamachi/qlot/pull/83

then probably we need to remove any mentions from the source code?

**Comment by fukamachi** [comment]
It was deleted when I rewrote Qlot from scratch because it seems to be not used so much.
Maybe I will add it again when I have time.

For the moment, I deleted the mentions from the command-line usage and README.

**Comment by svetlyak40wt** [comment]
Ok, thank you!
