### ISSUE TITLE
Add simple `qlot add ...` command to append new systems to .qlot file

### ISSUE THREAD

**Issue by egao1980** [fukamachi/qlot#116]
Please add simple 'add' CLI command that will add a line for a system to .qlot file and then trigger qlot install internally.

This will make it easier to use for quick projects - similar to npm or pipenv tools.

CLI args could be follow .qlot system dist syntax.
Examples:
```
qlot add ql mito
qlot add ultralisp cl-idna
qlot add github datafly fukamachi/datafly

....  
```

**Comment by fukamachi** [comment]
Good suggestion.
I remember someone is saying the same thing might be helpful.
I'll get right on it.

**Comment by fukamachi** [comment]
Perhaps we can add the upstream source by just specifying the library name when Quickdocs API is ready.  (like `qlot add mito` appends `github mito fukamachi/mito`)

**Comment by egao1980** [comment]
Thanks for working on this. We can just have a qlot file setting / line specifying the default source.
So the `qlot add mito` will work like that even before Quickdocks API is ready.

**Comment by fukamachi** [comment]
Custom configuration sounds overkill to me.

I'm thinking of this command-line argument notation inspired by NPM:

```
$ qlot add [<source>:]<project>[@<version>]

$ qlot add mito                              # => ql mito
$ qlot add ql:mito                           # => ql mito (same as the above)
$ qlot add ql:mito@2021-04-11                # => ql mito 2021-04-11
$ qlot add fukamachi/mito                    # => github mito fukamachi/mito
$ qlot add fukamachi/mito@1.0.1              # => github mito fukamachi/mito :tag 1.0.1
$ qlot add ultralisp:fukamachi/mito          # => ultralisp fukamachi-mito
$ qlot add git://github.com/fukamachi/mito   # => git mito git://github.com/fukamachi/mito
```

**Comment by egao1980** [comment]
For now using the same syntax as in qlot file is good enough - more typing but less confusion. Let's just have ql as a default in case we have only one argument to `qlot add`

**Comment by fukamachi** [comment]
Alright, then it's almost done.
