### ISSUE TITLE
Is it possible to add a relative filesystem path to Qlfile?

### ISSUE THREAD

**Issue by gwerbin** [fukamachi/qlot#119]
Suppose I am working on a project that bundles its dependencies in Git submodules:

```
./
  .git/
  README
  COPYING
  src/ ...
  t/ ...
  deps/
    depA/         <- git submodule
      thing-a.asd
      ...
    depB/         <- git submodule
      thing-b.asd
      ...
```

Is it possible to state a dependency on `./deps/depA` with Qlot?

Would I have to define my own distribution `.txt` file that refers to the contents of `deps/`? Can I use the `file://` scheme for that?

**Comment by fukamachi** [comment]
The feature will be added by #148.
