### ISSUE TITLE
qlot:install is failing in ABCL

### ISSUE THREAD

**Issue by santanuchakrabarti** [fukamachi/qlot#124]
Hi,

I git cloned qlot from GitHub in local-projects and loaded it with quicklisp. Then I created qfile with only one entry "ql alexandria" and ran (qlot:install :myproject). It is throwing the following error and I can't figure out how to fix it. I am new to Common Lisp and using ABCL as my implementation.

```
Installing Quicklisp to D:/santanu/programs/cl-codes/batch-exec/.qlot/ ...
; Fetching #<QL-HTTP:URL "http://beta.quicklisp.org/quicklisp.lisp">
; 55.80KB
==================================================
57,144 bytes in 0.06 seconds (945.84KB/sec)
#<THREAD "interpreter" {B31A888}>: Debugger invoked on condition of type PARAMETER-ERROR
  UIOP/LAUNCH-PROGRAM:LAUNCH-PROGRAM: I/O parameters cannot be foreign streams on this lisp
Restarts:
  0: TOP-LEVEL Return to top level.
```

**Comment by fukamachi** [comment]
It seems ABCL (plus also CLISP and Lispworks) doesn't allow streams for `:output` parameters of `uiop:launch-program`.

https://github.com/roswell/asdf/blob/02d5bdb9efae138b7b858e9642acf706b233b096/uiop/launch-program.lisp#L537-L540

**Comment by fukamachi** [comment]
Thank you for reporting. I fixed the problem at #125, and will merge it soon.

But, I still suggest you use SBCL instead of ABCL.

ABCL is not mainstream in the community. So it is common that libraries do not consider running on ABCL. This means that there are a lot of problems that users need to solve themselves.

Qlot uses Dexador for the HTTP client, Dexador uses CFFI for HTTPS communication, and CFFI doesn't go well with JVM. This can be a problem for you.

**Comment by santanuchakrabarti** [comment]
Thanks!! Please let me know once the fixes are ready. I shall fetch them to my cloned repository. 

However, I am looking for tools which are functional across different CL implementations. I don't want my development and build configuration to be bound to any particular implementation. So I am trying to use at least three different CL implementations to cross check my development. After all I think Common Lisp is about portability.

Thanks again!!

**Comment by fukamachi** [comment]
Okay, it's merged.

[Roswell](https://github.com/roswell/roswell) is the best for managing Lisp implementations.
I wrote an article about it before: [Day 1: Roswell, as a Common Lisp implementation manager](https://fukamachi.hashnode.dev/day-1-roswell-as-a-common-lisp-implementation-manager).

**Comment by santanuchakrabarti** [comment]
BTW I hope the changes has been committed to the master branch, right?
