### ISSUE TITLE
How to load my own lisp?

### ISSUE THREAD

**Issue by jcguu95** [fukamachi/qlot#127]
Due to a [problem](https://github.com/roswell/roswell/issues/524) I encountered with `ros`, instead of running lisp by invoking `ros`:

```
$ qlot exec ros -S . run
```

I'd like to run my own `sbcl`. However, a naive try `$ qlot exec
sbcl` leads to an error.

```
This is SBCL 2.0.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
fatal error encountered in SBCL pid 78566(tid 0x7fd9f4fd8740):
core was built for runtime "c4f5ae30faa6-root-2022-06-04-02-48-15" but this is "guu-jin-2022-06-30-15-56-39"
```

Why so, and is it possible to run my own lisp?

**Comment by fukamachi** [comment]
I don't understand why it happens while `qlot exec` doesn't do a lot to break other programs.
If you're `sbcl` command is nothing special, this command will be the same as `qlot exec`:

```common-lisp
$ sbcl --no-userinit --load .qlot/setup.lisp
```

[My blog post about Qlot](https://fukamachi.hashnode.dev/qlot-tutorial-with-docker) may be helpful.
