### ISSUE TITLE
Error: 'clack-handler-hunchentoot' is not available in dist

### ISSUE THREAD

**Issue by Neightro** [fukamachi/qlot#128]
I was testing out qlot in a test directory with nothing but this qlfile:

```
ql clack
ql ningle
ql clack-handler-hunchentoot
```
Upon running `qlot install`, I experience the error in the attached log. This was performed with a fresh installation (after running `rm -r` on .qlot). Afterward, I can see clack-handler-hunchentoot within .qlot/dists/quicklisp/systems.txt.

When running `(ql:quickload :clack-handler-hunchentoot)` from a REPL without qlot, it installs successfully.

Thanks in advance; I look forward to using qlot in my projects.

[qlot-install-error.txt](https://github.com/fukamachi/qlot/files/9126803/qlot-install-error.txt)

**Comment by fukamachi** [comment]
Well, `clack-handler-hunchentoot` is a system name, not a project name.
You don't have to add the `ql clack-handler-hunchentoot` line while `clack` project contains it.
