### ISSUE TITLE
  Error: 'reblocks' is not available in dist 'http://dist.ultralisp.org/ultralisp.txt'

### ISSUE THREAD

**Issue by gitthail** [fukamachi/qlot#133]
See title, can't find packages in ultralisp. I don't know why qlot is looking in that text file instead of resolving the links inside it.

qlfile:
`dist ultralisp http://dist.ultralisp.org/
ultralisp reblocks`

From the backtrace:
3: (ERROR QLOT/UTILS/SHELL:SHELL-COMMAND-ERROR :COMMAND ("/usr/local/bin/ros" "+Q" "-L" "sbcl-bin" "-e" "(require 'asdf)" "-e" "(setf *debugger-hook* (lambda (c parent) (declare (ignore parent)) (format *error-output* \"~&Error: ~A~2%\" c) (uiop/image:print-backtrace :condition c) (uiop/image:quit -1)))" "-e" "(push #P\"/Users/XXXXX/.roswell/local-projects/fukamachi/qlot/\" asdf/system-registry:*central-registry*)" "-e" #<(SIMPLE-BASE-STRING 212) (setf asdf/source-registry:*default-source-registries* (quote (asdf/source-registry:environment-source-registry asdf/source-registry:system-source-registry asdf/source-registry:system-source-registry-... {10023A5B2F}> ...) :CODE 255 :STDERR "Error: 'reblocks' is not available in dist 'http://dist.ultralisp.org/ultralisp.txt'
")

I'm not a programmer by profession and I don't really use github so if you need me to reformat or provide additional info I'll do my best.

**Comment by fukamachi** [comment]
Try `40ants/reblocks` since every project of Ultralisp has user names as naming conventions.
