### ISSUE TITLE
Dockerhub image only compiled with amd64 arch

### ISSUE THREAD

**Issue by Sasanidas** [fukamachi/qlot#164]
Testing the qlot image on a M1 Macbook, seems like the amd64 doesn't work as expected (I think it has to do some emulation for it to even run). 

Given that the SBCL image does have the target arm (https://hub.docker.com/r/fukamachi/sbcl/tags) and that qlot image is base on it( https://github.com/fukamachi/qlot/blob/master/Dockerfile#L1).

Would it be possible to add the arm64 target?

Thanks

**Comment by fukamachi** [comment]
I agree with you that it'd be great to have an ARM64 image. However, SBCL compilation doesn't go well on QEMU, and it makes it difficult to automate the release process on GitHub Actions.

I gave it a try: https://github.com/fukamachi/qlot/actions/runs/6648843958/job/18066454294.

**Comment by Sasanidas** [comment]
I see, the CI didn't work as expected, the error doesn't seem to provide too much information. Any clues on what can we do to make it work? 

Thanks

**Comment by fukamachi** [comment]
Eventually, I found a way to achieve it on GitHub Actions, and an ARM64 image is available from v1.5.3.
