### ISSUE TITLE
Git projects and line endings

### ISSUE THREAD

**Issue by mtstickney** [fukamachi/qlot#18]
First off, thanks for doing this project: it looks awesome, and I'm very much looking forward to using it.

There are some systems where line-endings are going to matter: SBCL on Windows doesn't know how to deal with CRLF as a line ending, so if you use multi-line strings you'll wind up with spurious `#\Return` characters in your strings. In a default install, git on windows will use `core.autocrlf=true` and checkout files with CRLF line endings (for example, if I clone the qlot repository on my windows machine it will fail because the dist files produce URLs with extra `\r` characters in them).

Does (or will) qlot have a way to specify that git sources should use a particular `autocrlf` setting when being checked out? If not, how should qlot consumers handle libraries that are sensitive to line-endings?

**Comment by fukamachi** [comment]
As I don't have a Windows machine, I can't get what is an actual problem.
Could you describe what is happening on your environment? Any errors?

**Comment by mtstickney** [comment]
Let say I have a file `foo.lisp`, with the following in it:
```
(defparameter +the-string+ "foo
bar
")
````

On windows the file will contain `#\Return` and `#\Linefeed` characters: if I `(load "foo.lisp")`, I get
````
+the-string+
;=> "foo^M
bar^M
"
````

That becomes an issue because SBCL doesn't know how to read `\r\n` as `#\Newline` on windows yet:
````
(with-input-from-string (stream +the-string+)
  (read-line stream))
;=> "foo^M"
````
Any system that tries to split things up by looking for `#\Newline` or using `READ-LINE` or similar is going to wind up with data with a trailing `#\Return` on it.

In qlot's case, this is an issue for the `PROJECT.TXT` and related methods. They return a multi-line string, the `#\Returns` aren't parsed out, and qlot tries to fetch a URL like `"/project.txt^M"`. The solution (for other projects as well) is to have git checkout the files with unix-style line endings by setting `core.autocrlf=input` or similar.

I don't know how this would play with other lisps, but it looks like quicklisp always uses unix-style line endings (I don't know if that's done purposely, or that it's just built on a unix machine). I'm not sure if that's the right way to handle this or not, but as-is you'd have to `QLOT:INSTALL` and then go re-checkout all your git-based sources with the right line endings, which seems like a usability problem.

**Comment by fukamachi** [comment]
Thanks, I got it.
I think just stopping using newlines in a string in the source code would work.

**Comment by mtstickney** [comment]
That would solve the issue for qlot, but it won't solve it for libraries that you're using in another project. I can't think of one off the top of my head, but if I use a git source in my qlotfile for a project that does use multi-line strings, it'd be nice to not have to go mess with git settings in the local quicklisp directory.

**Comment by fukamachi** [comment]
Ah, okay, that's a little bit complecated.
It seems "git" allows `--config` to specify a configuration for the new cloning repository, so using it like `git clone --config core.autocrlf=input <repo url>` would work, I think.

**Comment by mtstickney** [comment]
Neat, I hadn't noticed the `--config` option. I just tested it out on one of my boxes, and you'll probably want to use `git --config core.eol=lf --config core.autocrlf=input <repo url>`: apparently if `core.eol` is `crlf`, the `core.autocrlf=input` setting is considered a conflict and the checkout will fail.

**Comment by fukamachi** [comment]
Closing since I think this issue had been already resolved.
Feel free to reopen if there're still any problems.
