### ISSUE TITLE
qlot init fails when running from SBCL

### ISSUE THREAD

**Issue by rpgoldman** [fukamachi/qlot#197]
## Reproducible steps

1. Install `qlot` from quicklisp
2. Follow steps in instructions (modified for user mode) to install `qlot` command:
	a. `printf '#!/bin/sh\nexec sbcl --non-interactive --eval '(ql)' --eval "(ql:quickload :qlot/cli :silent t)" --eval "(qlot/cli:main)" "$@"\n' > ~/.local/bin/qlot` The differences are (1) no `sudo` (2) install to `~/.local/bin` instead of `/usr/local/bin` (3) `cl-user::ql` loads my quicklisp, which is not loaded by default in `.sbclrc`.
	b. `chmod +x ~/.local/bin/qlot`
    c. `which qlot` -> `/Users/rpg/.local/bin/qlot`
3. `qlot init` 

## Error messages
```
Command not found: init
Usage: qlot COMMAND [ARGS..]

COMMANDS:
    install
        Installs libraries to './.qlot'.

    update
        Makes './.qlot' up-to-date and update 'qlfile.lock'.
        Possible to update specific projects with --project option.
        ex) qlot update --project mito

    add [project name]
    add [source] [project name] [arg1, arg2..]
        Add a new library to qlfile and trigger 'qlot install'. (experimental)
        ex)
          $ qlot add mito       # Add 'ql mito'
          $ qlot add ql mito    # Same as the above
          $ qlot add ultralisp egao1980-cl-idna
          $ qlot add github datafly fukamachi/datafly

    run
        Starts REPL with the project local Quicklisp dists (Same as 'qlot exec ros run').

    exec [shell-args..]
        Invokes the following shell-command with the project local Quicklisp.

    bundle
        Bundles project dependencies to './.bundle-libs'.
        Load './.bundle-libs/bundle.lisp' to make them available.
        Read https://www.quicklisp.org/beta/bundles.html for the detail.

OPTIONS:
    --version
        Show the Qlot version
    --debug
        A flag to enable debug logging. (Only for 'install' or 'update')
    --no-deps
        Don't install dependencies of all systems from the current directory.
    --cache [directory]
        Keep intermediate files for fast reinstallation.
```

Possibly related:
```
$ qlot --version
This is SBCL 2.3.9, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
fatal error before reaching READ-EVAL-PRINT loop:
  C runtime option --version in the middle of Lisp options.
```

Maybe this only works with roswell?
## Versions:
 - Qlot version: `qlot-20220331-git`
 - Where did you get it from:  Quicklisp
 - OS: MacOS 13.6.2
 - Lisp: SBCL 2.3.9

**Comment by rpgoldman** [comment]
Wondered if `qlot init` was handled specially so did:

1. `touch qlfile`
2. `touch qlfile.lock`
3. `mkdir .qlot`
4. `qlot install clingon`

Now the error is: `qlot: File does not exist: clingon`

**Comment by rpgoldman** [comment]
Ah: the README is confusing. I should have done:

1. `qlot install`
2. `qlot add clingon`

**Comment by fukamachi** [comment]
Thank you for reporting.
Your Quicklisp dist seems to be old, so many things are different from the README on GitHub.
Please update it by `(ql:update-dist "quicklisp")`, or install it via other ways.
