### ISSUE TITLE
Installation fails because of tar --strip-component flag?

### ISSUE THREAD

**Issue by rpx99** [fukamachi/qlot#206]
## Describe the bug
Installation fails, due to unsupported _--strip-component_ flag of BSDs **tar** command. This seems to be GNU tar only.

## Reproducible steps
curl -L https://qlot.tech/installer | bash

## Error messages

Installation path: /home/rpx/.qlot
Downloading an archive from 'https://github.com/fukamachi/qlot/releases/download/1.3.6/qlot-1.3.6.tar.gz'...tar: WARNING! These patterns were not matched:
--strip-component
1
done
Setting it up. This may take a while...
Error: Setup process is failed. See '/home/rpx/.qlot/logs/install-1701702187.log' for the detailed logs.
Error: If it can be a bug, please report an issue at https://github.com/fukamachi/qlot/issues.

In install-1701702187.log:
bash: line 102: scripts/setup.sh: No such file or directory

## Versions:
 - Qlot version: 1.3.6
 - Where did you get it from: github
 - OS: OpenBSD 7.4 (current)
 - Lisp: SBCL 2.3.10

**Comment by fukamachi** [comment]
Fixed it at v1.3.10.
