### ISSUE TITLE
qlot fails with quicklisp installation method

### ISSUE THREAD

**Issue by rpx99** [fukamachi/qlot#208]
## Describe the bug

Installation with sbcl / quicklisp fails. The link exists, but ~/.qlot is empty.

`tron$ ls -la /home/rpx/.local/share/common-lisp/systems/qlot.asd 
lrwxr-xr-x  1 rpx  rpx  29 Dec  5 18:55 /home/rpx/.local/share/common-lisp/systems/qlot.asd -> /home/rpx/.qlot/qlot/qlot.asd`

## Reproducible steps

`sbcl --noinform --eval '(ql:quickload (list :qlot :qlot/distify))' --quit`

## Error messages

This is SBCL 2.3.10.openbsd.sbcl-2.3.10, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload (list :qlot :qlot/distify))

debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread" RUNNING {1003AB8003}>: Error while trying to load definition for system qlot from pathname /home/rpx/.local/share/common-lisp/systems/qlot.asd: Couldn't load #P"/home/rpx/.local/share/common-lisp/systems/qlot.asd": file does not exist.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry #<DEFINE-OP > on #<UNDEFINED-SYSTEM "qlot">.
  1: [ACCEPT                       ] Continue, treating #<DEFINE-OP > on #<UNDEFINED-SYSTEM "qlot"> as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the configuration.
  6: [ABORT                        ] Give up on "qlot"
  7: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
  8:                                 Exit debugger, returning to top level.

((LAMBDA (CONDITION) :IN PERFORM) #<SB-INT:SIMPLE-FILE-ERROR "~@<Couldn't load ~S: file does not exist.~@:>" {1001BB1B13}>)
   error finding frame source: Bogus form-number: the source file has probably changed too much to cope with.
   source: NIL
0] 

## Versions:
 - Qlot version: 1.3.6
 - Where did you get it from: github
 - OS: OpenBSD 7.4 (current)
 - Lisp: SBCL 2.3.10

**Comment by fukamachi** [comment]
Please write the more detailed steps to reproduce it.

* Where did you place the source code
* The output of `(asdf:system-source-directory :qlot)`
* Full stack trace

**Comment by rpx99** [comment]
I did not download additional source code. The quicklisp installation method does not say so.

Sorry, where do I need to download (the git repo of qlot?) to. 

I expected this is done with the quicklisp installation method.

**Comment by fukamachi** [comment]
This issue is stale. Create a new issue if you still have the same issue with the latest version.
