### ISSUE TITLE
Missing ~/.qlot directory on Linux

### ISSUE THREAD

**Issue by pamoroso** [fukamachi/qlot#216]
## Describe the bug

To uninstall Qlot I'm looking for the `~/.qlot/qlot/scripts/qlot-uninstaller.sh` script but there's no `~/.qlot` directory on my Linux system. I'm troubleshooting a [Lem](https://lem-project.github.io) issue and I'd like to uninstall Qlot to do a clean reinstall of Lem.

Lem is the only program I use Qlot with and I downloaded it as part of [installing Lem](https://github.com/lem-project/lem/issues/1065#issuecomment-1847125351). However, the only `~/.qlot` user directory I have is at `~/common-lisp/lem/.qlot` at the root of the directory tree where Lem is, and it contains no `scripts` directory:

```
paoloamoroso@penguin:~/common-lisp/lem$ ls .qlot/
asdf.lisp  dists       local-projects    quicklisp   source-registry.conf
bin        local-init  qlot-version.txt  setup.lisp  tmp
```

The Qlot script is `/usr/local/bin/qlot` and the rest of the files are in `/usr/local/lib/qlot/`:

```
paoloamoroso@penguin:~$ ls /usr/local/lib/qlot/
Dockerfile   local-init  qlot-tests.asd    README.markdown  scripts  tests
LICENSE.txt  qlot.asd    quicklisp-client  roswell          src
```

How do I uninstall Qlot manually? Can I just delete `/usr/local/bin/qlot` and the contents of `/usr/local/lib/qlot/`?

I could run `/usr/local/lib/qlot/scripts/qlot-uninstaller.sh` but I'm concerned it may wipe my home directory if it doesn't find `~/qlot`.

I use Crostini Linux, the Linux container of chromeOS currently based on Debian Bullseye.

## Reproducible steps

N/A

## Error messages

None.

## Versions:
 - Qlot version: 1.3.11
 - Where did you get it from: Automatic Installer
 - OS: Crostini Linux (Debian Bullseye)
 - Lisp: SBCL 2.3.8

**Comment by fukamachi** [comment]
As you pointed out, qlot-uninstaller.sh works only when the Qlot is installed in the user's home directory.
To uninstall in your case, delete these files:

* /usr/local/bin/qlot
* /usr/local/lib/qlot
* ~/.local/share/common-lisp/systems/qlot.asd or /root/.local/share/common-lisp/systems/qlot.asd

**Comment by pamoroso** [comment]
In the end I didn't need to uninstall Qlot as the Lem issue, a missing dependency, was easy for fix.

Anyway, on my Linux system both `~/.local/share/common-lisp/systems/qlot.asd` and `/root/.local/` are missing.

I'm closing this issue, thanks.
