### ISSUE TITLE
Unable to create shell command: "Symbol "INSTALL-SHELL-COMMAND" not found in the QLOT package"

### ISSUE THREAD

**Issue by flexibeast** [fukamachi/qlot#220]
This is on Gentoo: SBCL 2.3.5, installed from repos; fresh install of Quicklisp, installed via [the instructions on the Quicklisp site](https://www.quicklisp.org/beta/) (though `asdf:component-version` reports "20210213").

Following [the instructions for installing qlot via Quicklisp](https://github.com/fukamachi/qlot#via-quicklisp), installation via:
```
$ sbcl --eval '(ql:quickload (list :qlot :qlot/distify))' --quit
```
succeeded, but then trying to create a shell command fails:
```
$ sbcl --eval '(ql:quickload :qlot)' --eval '(qlot:install-shell-command #P"~/bin/")' --quit
This is SBCL 2.3.5, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "qlot":
  Load 1 ASDF system:
    qlot
; Loading "qlot"


debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD tid=15870 "main thread" RUNNING {10044901B3}>:
  Symbol "INSTALL-SHELL-COMMAND" not found in the QLOT package.

    Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(qlot:in...">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Use symbol anyway.
  1:            Ignore runtime option --eval "(qlot:install-shell-command #P\"~/bin/\")".
  2: [ABORT   ] Skip rest of --eval and --load options.
  3:            Skip to toplevel READ/EVAL/PRINT loop.
  4: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(SB-IMPL::READ-TOKEN #<SB-IMPL::STRING-INPUT-STREAM {7FDBE642F8B3}> #\q)
0] 
```

**Comment by fukamachi** [comment]
You’d better refer to the README on Quickdocs since the Quicklisp version is not up-to-date.
https://quickdocs.org/qlot#via-quicklisp

**Comment by flexibeast** [comment]
Following the "via Quicklisp" instructions on Quickdocs rather than the "via Quicklisp" instructions in this repo's README worked, thanks.

However, i'm not sure i understand what the issue was here. Are you saying that the Quicklisp version obtained by following the instructions at https://www.quicklisp.org/beta/ is not sufficiently recent to allow the instructions in the README to work, such that the instructions on Quickdocs need to be followed instead? If so, does that mean that the README should perhaps point users of the version of Quicklisp obtained via the quicklisp.org process to the Quickdocs instructions? Sorry if i'm misunderstanding ....

At any rate, closing.
