### ISSUE TITLE
Detection of Project Config

### ISSUE THREAD

**Issue by fosskers** [fukamachi/qlot#226]
## Describe the bug

Thank you for this project.

I noticed a discrepancy in behaviour between `qlot exec sbcl` and a raw `sbcl` call, at least when done through Sly/Slime. When a new Sly/Slime sessions is started directly from a Lisp file in a project, say `foo/src/main.lisp`, SBCL detects the `.asd` file in the project root (`foo/`) and loads correctly. However, qlot does not - it seems to need to be started from the project root itself (say, from within the `.asd` file instead). 

Checking qlot's error message, we see that it attempted to start itself from within the inner directory, not the project root:
```
Directory '/home/colin/code/common-lisp/filepaths/src/.qlot/' does not exist.
Run 'qlot install' to set up the project-local Quicklisp.
```
In this example, `.qlot/` does indeed exist, just one directory above.

Instead, I believe that `qlot` should somehow detect the project root and look for its config files there instead.

## Reproducible steps

1. Have Sly configured as advertised in qlot's README:

```
  (setq sly-default-lisp 'sbcl
        sly-lisp-implementations '((sbcl ("sbcl") :coding-system utf-8-unix)
                                   (qlot ("qlot" "exec" "sbcl") :coding-system utf-8-unix))))
```
2. From a fresh Emacs session (with no running Slynk sessions), open a Common Lisp project and navigate directly to a Lisp file.
3. Attempt to launch a `sly` session, choosing the `qlot` option.
4. See an error similar to the one pasted above.

## Error messages

(see above)

## Versions:
 - Qlot version: 1.4.1
 - Where did you get it from: https://aur.archlinux.org/packages/qlot
 - OS: Arch Linux
 - Lisp: 2.3.11

**Comment by fukamachi** [comment]
Thank you for reporting!

Yep, you need to execute `M-x cd RET /path/to/project` before launching it.
As I don't use Emacs usually, I'm happy to hear your suggestion :)

However, I don't know if it's possible to pass a directory to the Lisp process through SLIME/Sly.
I'll look into the code. I'd be glad to hear if you have any ideas to achieve.

**Comment by fosskers** [comment]
Mostly what I'm suggesting is that perhaps `qlot` should:

1. Look for its files in `.` (現状). 
2. If it can't find them, look in `..`, at least until it can find a "project root" or give up.
  - For example, it could look until it finds a `*.asd` file or a `.git/` directory.
3. It could continue until it reaches `/home/YOU/`, `/`, or give up after a set number of `..` jumps.

What do you think?

**Comment by fukamachi** [comment]
It seems I'm missing something, but is it okay to assume the `*default-pathname-defaults*` is the directory of the active buffer on Emacs?
Then, it's much easier than I expected.

**Comment by fosskers** [comment]
When I open my project's `.asd` first before anything else and start Sly:
```
CL-USER> *default-pathname-defaults*
#P"/home/colin/code/common-lisp/filepaths/"
```
When I open a file _within_ the project first and start Sly:
```
CL-USER> *default-pathname-defaults*
#P"/home/colin/code/common-lisp/filepaths/src/"
```

**Comment by fosskers** [comment]
Thank you!
