### ISSUE TITLE
Error when using qlot from different user accounts

### ISSUE THREAD

**Issue by lucashpandolfo** [fukamachi/qlot#23]
Qlot uses the ```/tmp/qlot/``` directory for some temp files.
If I first run qlot with user ```A```, then the directory is created with user ```A``` ownership, but then if I want to use qlot with ```B``` user I get:

```lisp
debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1003D96473}>:
  error opening #P"/tmp/qlot/quicklisp-P1XHZTTF.lisp": Permission denied
```

Can the directory be changed to something like ```/tmp/qlot-A``` and ```/tmp/qlot-B```?

**Comment by fukamachi** [comment]
The problem had been fixed at https://github.com/fukamachi/qlot/commit/b97977f82d19cc0be081bc39ea57136cf74a3a90, which is included in the latest Quicklisp dist (2015-08-04).
Update it with `(ql:update-dist "quicklisp")` and try it again.

**Comment by lucashpandolfo** [comment]
Well... seems reasonable, but I'm utterly confused:

```common-lisp
* (ql:update-dist "quicklisp")

You already have the latest version of "quicklisp": 2015-08-04.
NIL
* (asdf:system-source-directory :qlot)

#P"/home/testuser/quicklisp/dists/quicklisp/software/qlot-20150804-git/"
* (ql:quickload 'qlot-install)
To load "qlot-install":
  Load 1 ASDF system:
    qlot-install
; Loading "qlot-install"
........................
(QLOT-INSTALL)
* qlot.tmp:*tmp-directory*

#P"/tmp/qlot/"
```

```bash
testuser@Phy:~> cat quicklisp/dists/quicklisp/software/qlot-20150804-git/src/tmp.lisp 
(in-package :cl-user)
(defpackage qlot.tmp
  (:use :cl)
  (:export :*tmp-directory*
           :tmp-path))
(in-package :qlot.tmp)

(defparameter *tmp-directory* #P"/tmp/qlot/")

(defun tmp-path (&rest pathnames)
  (reduce #'merge-pathnames
          (reverse pathnames)
          :initial-value *tmp-directory*
          :from-end t))
```

But looking at the github source tree is clear to me that qlot is not the one on fault.
I'll try looking elsewhere.

**Comment by fukamachi** [comment]
I just looked into the latest Quicklisp dist, and found out the change isn't included in it.
Probably there's some delay between getting library source code and actually releasing a dist.
You have to get the latest version from GitHub for trying it.

Or, binding `qlot.tmp:*tmp-directory` to something else would work for workaround.
