### ISSUE TITLE
`qlot exec ecl` fails

### ISSUE THREAD

**Issue by fosskers** [fukamachi/qlot#250]
## Describe the bug

Any attempt to use `ecl` fails. A condition similar to this is thrown:
```
An error occurred during initialization:
Reader error in file #<input stream #P"/home/colin/code/common-lisp/filepaths/.qlot/local-init/qlot-99-setup.lisp" 0x71cd43265a00>, position 1920:
Cannot find the external symbol REGISTERED-SYSTEM in #<"ASDF/INTERFACE" package>..
```
The actual problem is that within `.qlot/local-init/qlot-99-setup.lisp`, `asdf:registered-system` is called. Unfortunately, since ECL bundles an old asdf `3.1`, that function is not exposed. See https://gitlab.com/embeddable-common-lisp/ecl/-/issues/749 .

A quick check of the major implementations shows:

```
sbcl  3.3.1
abcl  3.3.6
ccl   3.3.3
clasp 3.3.6
ecl   3.1.8.8
```

Note that, at least for `#+ecl`, calling `asdf::registered-system` (two colons) instead works. 

Related: https://github.com/fukamachi/qlot/issues/245#issuecomment-2143469524

## Reproducible steps

1. Run `qlot exec ecl`.
2. See the condition.

## Error message
See above.

## Versions:
 - Qlot version: 1.5.5
 - Where did you get it from: AUR / source
 - OS: Arch Linux
 - Lisp: ECL 23.9.9

**Comment by fukamachi** [comment]
Thank you for reporting!
Very informative. I'll work on it, and hopefully, it will be fixed soon.

**Comment by fosskers** [comment]
Thank you for your quick response! I hope you're sleeping now haha.
