### ISSUE TITLE
A qlot failure when building lem editor

### ISSUE THREAD

**Issue by pakhomovaleks** [fukamachi/qlot#259]
## Describe the bug
A failure when trying to build lem editor from source
## Reproducible steps
See https://lem-project.github.io/installation/ncurses/linux/:

mkdir $HOME/common-lisp && cd $HOME/common-lisp
git clone https://github.com/lem-project/lem.git
cd lem && make ncurses

## Error messages
Downloading "https://beta.quicklisp.org/archive/cl-interpol/2022-11-06/cl-interpol-20221106-git.tgz".
Unexpected error: A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X017786D0) (SSL_get_error: 1). ERR_print_errors(): 00107E81AC7C0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s:

This can be a bug of Qlot.
Report it at https://github.com/fukamachi/qlot/issues/new/choose.
Please attach the stack trace dumped to '/tmp/qlot-error-AR3FSGEY.log'.

## Versions:
 - Qlot version: 1.5.8
 - Where did you get it from: Automatic Installer
 - OS: Ubuntu 22.04.3 LTS (Kubuntu)
 - Lisp: sbcl 2.1.11.debian (same failure with sbcl 2.4.6)
[qlot-error-FHHK787Z.log](https://github.com/user-attachments/files/16323835/qlot-error-FHHK787Z.log)

**Comment by fukamachi** [comment]
It's possibly due to a network problem.
https://github.com/lem-project/lem/issues/1195

**Comment by fukamachi** [comment]
It may be fixed at #275 in the next release.

**Comment by fukamachi** [comment]
Fixed in [1.5.11](https://github.com/fukamachi/qlot/releases/tag/1.5.11).
