### ISSUE TITLE
Using github libraries newer that Quicklisp's

### ISSUE THREAD

**Issue by wnortje** [fukamachi/qlot#26]
How do I use a library from github which is newer than the Quicklisp one? QLOT always takes the oldest one it can find.

My qlfile
```
ql :all 2015-08-04
git crane https://github.com/eudoxia0/crane.git
```
The last version of Crane is not yet in Quicklisp.

**Comment by wnortje** [comment]
I found a work-around. If you leave out the ```ql :all 2015-08-04``` and only specify the ```crane``` line then the correct version of crane is used with the latest version of QL. I then edit the qlfile.lock file to specify the 2015-08-04 version of QL and run ```(ql:install)```.

It will be really useful if you can specify which library should be used when it is supplied by multiple dists instead of just using the oldest one, or if you can say "use all the libraries from QL except this one"

**Comment by fukamachi** [comment]
> If multiple distributions provide the same library, lower one would take priority over higher ones.
https://github.com/fukamachi/qlot#priorities-of-distributions

What happens if reversing the order of those lines?

**Comment by wnortje** [comment]
I can't reproduce the problem again. Quicklisp version is "2015-10-31". I am closing the issue.

> If multiple distributions provide the same library, lower one would take priority over higher ones.
> https://github.com/fukamachi/qlot#priorities-of-distributions

What does 'lower one' refer to? Is it the version of the library or the position in the qlfile?

**Comment by fukamachi** [comment]
> What does 'lower one' refer to? Is it the version of the library or the position in the qlfile?

It means the position in the qlfile.

**Comment by wnortje** [comment]
> It means the position in the qlfile.

OK, that is not what I understood. Then my feature request

>It will be really useful if you can specify which library should be used when it is supplied by multiple dists instead of just using the oldest one, or if you can say "use all the libraries from QL except this one"

is not necessary.
