### ISSUE TITLE
Github returns "403 Forbidden" error

### ISSUE THREAD

**Issue by Junker** [fukamachi/qlot#264]
## Describe the bug
When using many dependencies from GitHub, GitHub may temporarily ban your IP, resulting in an error message such as: `Unexpected error: An HTTP request to "https://api.github.com/repos/User/repo" returned 403 Forbidden.`

## Reproducible steps
- create qlfile with many github entries
- start `qlot install`

## Error messages
Unexpected error: An HTTP request to "https://api.github.com/repos/User/repo" returned 403 forbidden.

## Versions:
 - Qlot version: 1.5.8
 - Where did you get it from: ArchLinux AUR
 - OS: Archlinux
 - Lisp: SBCL 2.4.6

## Thoughts
Maybe should add the ability to provide Github API token to bypass limits.

**Comment by fukamachi** [comment]
Thank you for reporting.
Qlot uses an environment variable `GITHUB_TOKEN` when making a request if it's set.

**Comment by Junker** [comment]
Thanks! 
I think should add information about it to the README.
