### ISSUE TITLE
Documentation: How to install based on qlfile.lock instead of qlfile?

### ISSUE THREAD

**Issue by daninus14** [fukamachi/qlot#274]
Hi, in order for all developers to have the same state, I would like qlot to install based on the current configuration of the qlfile.lock.

This is one of the goals described in the docs.

However `qlot install` works based on the `qlfile` and not the `qlfile.lock` which makes it so different computers have different states and sometimes things break.

How do we install based on the `qlfile.lock`? 

Can you please add it to the docs? If you answer the question I could add it to the wiki if you want me to

**Comment by fukamachi** [comment]
As README describes, `qlot install` uses `qlfile.lock` if it exists. It refers `qlfile` partially only when it's updated since `qlfile.lock` was generated.

**Comment by daninus14** [comment]
Thanks! I was trying to replicate a repository in another server only to realize that by closing the running lisp image somehow I can't run it again! So I'll close this issue. 

I'm having an issue with qlot install using dexador which gives me a compile time issue saying `bt2` in the `connection-cache.lisp` file does not exist. Not sure why this could be since bordeaux-threads is definitely there
