### ISSUE TITLE
Error using :ref in qlfile trying to update LEM

### ISSUE THREAD

**Issue by rpx99** [fukamachi/qlot#278]
## Describe the bug

```
tron$ gmake sdl2 
qlot install
Reading '/home/rpx/lisp/lem/qlfile'...
⨯ [1/1] cl-sdl2-image  Failed to install

Unexpected error: Error while executing a shell command: "git" "-C" "/tmp/qlot-EA7BH2OR/cl-sdl2-image-ref-3963be863e1df371b2c3f17f1bc59bc572c5954b/" "checkout" "3963be863e1df371b2c3f17f1bc59bc572c5954b" "--quiet" (Code=128)

  fatal: unable to read tree (3963be863e1df371b2c3f17f1bc59bc572c5954b)
```

## Reproducible steps

Updated LEMs qlfile like so:

`git cl-sdl2-image https://github.com/lem-project/cl-sdl2-image.git :ref 3963be863e1df371b2c3f17f1bc59bc572c5954b`

Is this wrong? If I put the new value it in the qlfile.lock it gets overwritten each time ?

("cl-sdl2-image" .
 (:class qlot/source/git:source-git
  :initargs (:remote-url "https://github.com/lem-project/cl-sdl2-image.git")
  :version "git-8734b0e24de9ca390c9f763d9d7cd501546d17d4"))

## Versions:
 - Qlot version: 1.5.8
 - Where did you get it from: Automatic Installer
 - OS: OpenBSD Current
 - Lisp: SBCL 2.4.8.openbsd.sbcl-2.4.8

**Comment by fukamachi** [comment]
The commit is deleted on GitHub.

https://github.com/lem-project/cl-sdl2-image/commit/3963be863e1df371b2c3f17f1bc59bc572c5954b

<img width="916" alt="Screenshot 2024-09-17 at 10 26 25" src="https://github.com/user-attachments/assets/eb38d13d-bf5d-48e5-a67f-21d694ecc964">

**Comment by rpx99** [comment]
Oh, I did not notice that LEM uses a fork of the original repo https://github.com/lispgames/cl-sdl2-image
The fork is too old - thanks!
