### ISSUE TITLE
Should qlot install dependencies ?

### ISSUE THREAD

**Issue by krsanky** [fukamachi/qlot#283]
qlot add jzon

Now when I build a project in a SBCL repl like: (asdf:load-system 'my-proj)
It makes me install all of the dependencies of jzon before it will build.

qlot add flexi-streams
qlot add float-features
qlot add trivial-features
...

But if I look here:
https://quickdocs.org/jzon?tab=systems

Those dependencies should be installed with jzon ?

Should qlot install dependencies of a library like quicklisp does ?

**Comment by fukamachi** [comment]
Thank you for reaching out.
See https://github.com/fukamachi/qlot/issues/221.

Note: I need to add this to the FAQ later.

**Comment by krsanky** [comment]
Thank you, I'll try those things.
Thanks!
