### ISSUE TITLE
dumb http transport does not support shallow capabilities

### ISSUE THREAD

**Issue by loskool** [fukamachi/qlot#286]
## Describe the bug

`qlot install` fails with a git error when cloning over https a repositories managed by [cgit](https://github.com/danrue/cgit).

## Reproducible steps
   
    mkdir qlot-fails
    cd qlot-fails
    qlot init
    echo git petty-types https://cicadas.surf/cgit/colin/petty-types.git >> qlfile

and put the following int `qlot-fails.asd`:

``` lisp
;; qlot-fails/qlot-fails.asd

(asdf:defsystem #:qlot-fails
  :depends-on (petty-types))

```

Then run `qlot install`

## Error messages

```
● [1/1] petty-types  
● [1/1] petty-types  Installing "petty-types".
● [1/1] petty-types  Determining the project version.
● [1/1] petty-types  Writing the distinfo.
● [1/1] petty-types  Running git clone.
⨯ [1/1] petty-types  Failed to install

Unexpected error: Error while executing a shell command: "git" "clone" "--depth" "1" "--recursive" "--quiet" "--config" "core.eol=lf" "--config" "core.autocrlf=input" "https://cicadas.surf/cgit/colin/petty-types.git" "/tmp/qlot-I17Q2KK1/petty-types-ref-3394261352a6103c8969f1cd938135a03754cf0b/" (Code=128)

  fatal: dumb http transport does not support shallow capabilities

This could be a bug in Qlot.
Report it at https://github.com/fukamachi/qlot/issues/new/choose.
Please attach the stack trace dumped to '/tmp/qlot-error-AR3FSGEZ.log'.
```
[qlot-error-AR3FSGEZ.log](https://github.com/user-attachments/files/17198904/qlot-error-AR3FSGEZ.log)

## Versions:
 - Qlot version: 1.5.12 
 - Where did you get it from: Automatic Installer
 - OS: Debian 12
 - Lisp: 2.3.5

**Comment by loskool** [comment]
Could we add an option to the qlfile syntax for git entries to support excluding the `--depth` git option from the git command constructed in `utils/git.lisp` ?

Something like 

    git some-repo https://cool-repos.com/some-repo.git :shallow false

?

**Comment by loskool** [comment]
Thanks much!

**Comment by loskool** [comment]
@fukamachi 

This does make a retry, but at the next step when git fetches with `--unshallow` git gives the error that unshallow makes no sense on a full repository.

I made this change to get it working locally:

[unshallow.diff.txt](https://github.com/user-attachments/files/17229989/unshallow.diff.txt)

**Comment by fukamachi** [comment]
Oh, you're right! I'm going to fix it.
