### ISSUE TITLE
Is it possible to install git/github dependencies as "editablle"?

### ISSUE THREAD

**Issue by svetlyak40wt** [fukamachi/qlot#29]
They should have their .git subdirectory remaining after installation.

**Comment by fukamachi** [comment]
No, it's not.
Qlot ignores `.git/` directory and considers the libraries won't be changed.

**Comment by svetlyak40wt** [comment]
May be it well be useful to add this feature?

The only way I found currently, is to install the library with roswell, like this: `ros install 40ants/sigil`, but in this case, it is installed system-wide, into the `~/.roswell/local-projects`.

**Comment by fukamachi** [comment]
It may be useful in some cases, but I'm still not sure Qlot has the feature.
Have you tried git submodule/subtree?

**Comment by svetlyak40wt** [comment]
I know about git submodules, but they aren't that convenient.

For example, imagine, I have a project which uses qlot and installs it's dependencies in specified in qlfile. Working on the project you decide to experiment/fix some of the dependencies, hit M-. in emacs, open it's sources, edit, evaluating code, etc. After the fix is ready, and you want to propose a pull-request for the dependency what you need to do?

1. Now you have to clone this system somewhere else.
2. Figure out which files you've changed during the hacking session.
3. Copy them to the cloned repository.
4. Commit/push/send a pull-request.

If qlot will install code from git as a repository, with `.git` inside, then most of these movements are unnecessary, you just:

1. Run git remote add my url-of-the-fork
2. Commit/push/send a pull-request.

**Comment by svetlyak40wt** [comment]
Eitaro, what do you think about this issue? Should be closed, or better to leave it as a "feature request"?

**Comment by svetlyak40wt** [comment]
Ok, I think the task could be solved by https://github.com/roswell/ql-checkout.
