### ISSUE TITLE
Should `system-index.txt` be ignored?

### ISSUE THREAD

**Issue by daninus14** [fukamachi/qlot#295]
I find that by doing `qlot install` I get git differences in `system-index.txt` every time. Is this expected? Should it be ignored?

One machine is a mac and the other ubuntu, pulling the same repo and doing `qlot install` yields a different `system-index.txt`. 

For context: this `system-index.txt` is in the root directory of the project which also contains the `.qlot/` directory and the `qlfile`.

**Comment by fukamachi** [comment]
It is not supposed to be created. Is the directory added to Quicklisp's local projects?
Please write reproducible steps.

**Comment by daninus14** [comment]
Oh, maybe I messed up my setup?

I have the project in a non quicklisp folder, just in a personal folder, and I load the project in the REPL (slime) by:

```common-lisp
(pushnew 
 (truename "/home/mydir")
 ql:*local-project-directories*)
```

I'm pretty sure I did something like `qlot init` in the folder originally, and then added systems by using `qlot install` or in the REPL doing `(ql:quickload "system-name")`.

I start the repl with `qlot exec ros run` or something of that sort so that the quicklisp loaded should be the one from qlot.

**Comment by daninus14** [comment]
By the way, now that you enabled discussions, should I move this over there?

**Comment by fukamachi** [comment]
That's the thing. Quicklisp makes system-index.txt for local projects to cache system names to load them quickly.

**Comment by daninus14** [comment]
Ah this is fantastic, I just realized qlot was already adding my main folder by doing `qlot exec ros run`, so I basically can just do `(ql:quickload "myproject")` without adding it. I didn't know. I had that from before I was using qlot. Thanks for the help 😄
