### ISSUE TITLE
Non-string system dependencies

### ISSUE THREAD

**Issue by mtstickney** [fukamachi/qlot#33]
I've just noticed that in the latest quicklisp release, the cffi-toolchain system depends on the system `(:VERSION "asdf" "3.1.2")`, which breaks qlot's `ensure-installed-in-local-quicklisp`. `ensure-installed-in-local-quicklisp` tries to `string-downcase` the system name, which in this case is a list rather than a string.

I'm not quite sure what the fix is here. Supporting versioned dependencies would mean coming up with some sort of versioned object to pass to `ql-dist:ensure-installed` -- there are other issues with versioned systems, but I think that's quicklisp/asdf's problem. Things might be trickier if the dependency is coming from a non-quicklisp system pulled in by qlot, though.

**Comment by fukamachi** [comment]
This issue is stale. Reopen if you still have the same issue with the latest version.
