### ISSUE TITLE
Submodule problem

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/qlot#38]
When I try to clone qlot today, I get a submodule problem:

No submodule mapping found in .gitmodules for path 'tests/tmp/quicklisp/tmp/qlot/86F1A8FB/source-git/repos/cl-dbi-ref-54928984e5756e92ba298aae51de8b95a6b0cf4b'

Do you know what it means? How can I get around it?

**Comment by fukamachi** [comment]
Temporary directory for testing was included in the repository, though it shouldn't be.
I deleted it at the above commit.
