### ISSUE TITLE
qlot exec set's CL_SOURCE_REGISTRY to empty string in ClozureCL and to a full path in SBCL

### ISSUE THREAD

**Issue by svetlyak40wt** [fukamachi/qlot#48]
The problem is that if `CL_SOURCE_REGISTRY` is an empty string, then [ASDF's system search skips it](https://common-lisp.net/project/asdf/asdf/Shell_002dfriendly-syntax-for-configuration.html) and searches libraries at default places such as `~/common-lisp/`:

```
[+|art@art-osx5:~]% ros use sbcl-bin
[+|art@art-osx5:~]% qlot exec env | grep SOURCE
CL_SOURCE_REGISTRY=/Users/art/
[+|art@art-osx5:~]% ros run --eval '(princ (list (lisp-implementation-type) (lisp-implementation-version)))'
(SBCL 1.3.21)

[+|art@art-osx5:~]% ros use ccl-bin
[+|art@art-osx5:~]% qlot exec env | grep SOURCE
CL_SOURCE_REGISTRY=
[+|art@art-osx5:~]% ros run --eval '(princ (list (lisp-implementation-type) (lisp-implementation-version)))'
(Clozure Common Lisp Version 1.11-r16635  (DarwinX8664))
```

This leads to the following behaviour – when CCL is started like `qlot exec ros run`, then it loads libraries from `~/common-lisp/`, but SBCL, started the same way, does not see them.

What is the **expected** behaviour for `qlot exec`???

**Comment by svetlyak40wt** [comment]
I this replacing this line https://github.com/fukamachi/qlot/blob/f95f752eeb332d4b2ee89d2243a093aeacbd7762/roswell/qlot.ros#L67

with
```
(setenv "CL_SOURCE_REGISTRY" (namestring (probe-file *default-pathname-defaults*)))
```

will make behaviour of CCL the same like SBCL's.

**Comment by windymelt** [comment]
+1
