### ISSUE TITLE
Manage ASDF versions

### ISSUE THREAD

**Issue by ruricolist** [fukamachi/qlot#52]
Suggestion: I think it should be possible to specify a minimum ASDF version in the Qlfile, and have Qlot fetch and install it if necessary.

It's nice to be able to depend on a particular version of a library. But if that library expects a recent version of ASDF, and the Lisp I'm using only supplies an older implementation, then I'm back in dependency hell.

**Comment by fukamachi** [comment]
It's out of the scope of Qlot.
Perhaps, Roswell would have such feature? CC @snmsts

**Comment by snmsts** [comment]
``ros install asdf/version`` (version would be like 3.3.1.1) will install specified version.

**Comment by ruricolist** [comment]
Thanks @snmsts, that solves my problem.
