### ISSUE TITLE
Travis checks are broken – they are showed as green when some tests were failed

### ISSUE THREAD

**Issue by svetlyak40wt** [fukamachi/qlot#60]
For example, this build for SBCL has failed if you look into the log:

https://travis-ci.org/fukamachi/qlot/jobs/422395405

But Travis thinks it is OK and shows that everything is ok with this pull-request.

**Comment by svetlyak40wt** [comment]
I think, the problem is in the line:
```
ros -s rove -e '(rove:run :qlot/tests)'
```

Which does not return a exit status code.

In one of my projects, [I use a command line utility](https://github.com/40ants/defmain/blob/master/.travis.yml#L49)  `rove` and it does return code: https://travis-ci.org/40ants/defmain

**Comment by fukamachi** [comment]
Thank you for pointing out.
I reverted the change to .travis.yaml.

**Comment by fukamachi** [comment]
I've fixed the issue and now it passed on the master branch.

**Comment by svetlyak40wt** [comment]
Now everything is OK.
