### ISSUE TITLE
Installs broken after bb15def233142bd9c6e0aebe79d055d0e9b6bcd4

### ISSUE THREAD

**Issue by mtstickney** [fukamachi/qlot#63]
Commit bb15def233142bd9c6e0aebe79d055d0e9b6bcd4 attempts to load a project after installing the sources for it. Some things, like fetching quicklisp dependencies (e.g. so that a manifest file will actually have systems in it) need this, but unfortunately it can also cause installs to fail.

The trouble is that qlot will be loading the projects dependencies, which might overlap the systems that qlot itself depends on. For example, I have a project with an older quicklisp dist in it; when doing a `qlot:install`, the load fails because the version of `usocket` in the project is older than the version `qlot` loaded from the system quicklisp dist. The packages are different, which causes SBCL to signal an error.

I'm not sure that there's a good fix for this, short of having users load the system when qlot is not also loaded (in my build systems, I need three separate steps: one to `qlot:install`<sup>1</sup>, one to `qlot:quickload` and write a manifest file, and one to build from the manifest). In general, there seem to be a lot of potential issues here, because it isn't really possible to inspect the systems a project makes available without loading them, but loading them might conflict with code that qlot depends on.

This is something I still need to think about more, but there are a couple of potential solutions for the general problem that I can think of:
1. Only load systems with something like Robert Strandh's [environments](http://metamodular.com/environments.pdf), so the loaded system is isolated from qlot -- this is part of the [SICL](https://github.com/robert-strandh/SICL) implementation, but I don't think it's ready to be used yet.
2. Don't depend on any external systems in qlot. This is the approach ASDF and quicklisp take, where any code they use is part of the system itself. This is obviously more work, but you won't get dependency conflicts.
3. If all you want to do is have quicklisp fetch dependencies, you could take buildapp's approach and start a secondary lisp process that only loads enough code to redirect the quicklisp home directory, and not any additional dependencies. This may not work if you need to load the system to do something like generate a system index. Now that I think about it a little, maybe this works better by starting a secondary process to perform the source installation, since that's a fairly distinct task.
4. Use a `*macroexpand-hook*` to add a prefix to the package name in every `defpackage` form. There are all kinds of reasons this is a bad idea (like the fact that most systems probably assume the package name is the one they specified in the source code), but it's worth thinking about.

Items 3 & 4 are both cheater versions of 1, which is probably the proper way to do this. Unfortunately first-class environments in lisp are probably not going to be widely available any time soon.

<sup>1</sup> `qlot:install` loads additional systems to fetch sources, so doing a `qlot:quickload` in the same session as a `qlot:install` can cause conflicts where a plain `qlot:quickload` doesn't.

**Comment by fukamachi** [comment]
Thank you for the detailed report.

I think `ql-dist:ensure-installed` without actually loading dependencies would work.
If not, 3 sounds good to me and easy to implement in case of depending on Roswell.

**Comment by fukamachi** [comment]
Could you check if the 'master' branch works?

**Comment by mtstickney** [comment]
It does. It also appears to mitigate the issue in #62, although I'm not exactly sure why, yet.
