### ISSUE TITLE
Failed to get a value of DISTINFO-TEMPLATE-URL for http://beta.quicklisp.org/dist/quicklisp/2019-01-07/distinfo.txt distribution.

### ISSUE THREAD

**Issue by tssund93** [fukamachi/qlot#72]
Right now getting this on Mac OS when running `qlot install` but have also seen this error on Windows.  Looking at http://beta.quicklisp.org/dist/quicklisp/2019-01-07/distinfo.txt, it does seem to be missing a distinfo-template-url field.

**Comment by fukamachi** [comment]
To shorten the time to investigate and fix, could you tell me these informations?

- The version of Qlot you're using
- Steps to reproduce the error
  - In this case, reproducisble `qlfile` would be okay

**Comment by tssund93** [comment]
I'm using Qlot 0.9.9 and a minimal reproducible qlfile is:

```
ql :all 2019-01-07
ql drakma :latest
```

It seems to consistently happen if I run `qlot install` more than once, even if I've added new dependencies to the `qlfile`.  Sometimes it also fails the first time, but this might only be when `qlfile.lock` exists, I'm not sure yet.  It seems like the workaround is to just always use `qlot update` after the initial install once it works because it seems to be consistent, but it would be nice if there was a more helpful error when running `qlot install`.
