### ISSUE TITLE
Meta: cl-notebook no longer builds

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/qlot#95]
[cl-notebook](https://github.com/inaimathi/cl-notebook/) recently stopped building even though it has not been visibly changed since March. 

The error is:
 ```
; caught ERROR:
;   READ error during COMPILE-FILE: Package QLOT/UTIL does not exist. Line: 109, Column: 41, File-Position: 4215 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/cl-notebook/ddee9b7876e1ce489b09165910c76abe2301cc7f/cl-notebook-20191121-git/src/model.lisp" {100E2AA373}>
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10005604C3}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-notebook" "src" "model">
```

How should cl-notebook be updated to work properly with the changes to qlot? Or, is there any way qlot can restore something so that cl-notebook builds again?

**Comment by notmgsk** [comment]
An issue remains: http://report.quicklisp.org/2019-11-28/failure-report/cl-notebook.html#cl-notebook

Looks like the symbol `INSTALL-QUICKLISP` has moved.  I have a [PR](https://github.com/inaimathi/cl-notebook/pull/72/files) open, but the author hasn't responded.
